parameters:
- name: 'stageTitle'
  type: string
  default: ''
- name: 'resourceGroup'
  type: string
  default: ''
- name: 'region'
  type: string
  default: 'North Central US'
- name: 'storageAccountName'
  type: string
  default: ''
- name: 'storageAccountType'
  type: string
  default: 'Standard_LRS'
- name: 'appName'
  type: string
  default: ''

stages:
- stage: ${{parameters.stageTitle}}
  jobs:
  - job: 'backend_infra'
    pool:
      vmImage: 'windows-latest'
    steps:     
    
    - task: AzureCLI@2
      displayName: 'Get Azure Search Query Key'
      inputs: 
        azureSubscription: 'whitewaterfinder-sp'
        scriptType: ps
        scriptLocation: 'scriptPath'
        ScriptPath: 'whitewaterfinder.infrastructure/getazuresearchkey.ps1'
        ScriptArguments: 'brgs-global'   

    - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: 'Replace tokens in azuredeploy.json'
      inputs:
        rootDirectory: 'whitewaterfinder.infrastructure/'
        targetFiles: azuredeploy.json
        tokenPrefix: '{%%'
        tokenSuffix: '%%}'     

    - task: AzureResourceGroupDeployment@2
      displayName: 'Deploy backend ARM Template'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        resourceGroupName: '${{parameters.resourceGroup}}'
        location: '${{parameters.region}}'
        csmFile: 'whitewaterfinder.infrastructure/azuredeploy.json'
        csmParametersFile: 'whitewaterfinder.infrastructure/parameters.json'
        overrideParameters: '-storageAccountName ${{parameters.storageAccountName}} -storageAccountType "${{parameters.storageAccountType}}" -appName "${{parameters.appName}}" -appPlanName "WaterFinderPlan" -preferencesApp "dev-paddle-finder-preferences"  -azureSearchKey $(searchKey)'       

    - task: AzureResourceGroupDeployment@2
      displayName: 'Deploy AKV'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        resourceGroupName: '${{parameters.resourceGroup}}'
        location: '${{parameters.region}}'
        csmFile: 'whitewaterfinder.infrastructure/kvtemplate.json'
        csmParametersFile: 'whitewaterfinder.infrastructure/kvparameters.json'
        overrideParameters: '-tenantId "$(tenantId)" -adminId "$(adminId)"'

  - job: 'bot'
    dependsOn: 'backend_infra'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: 'Replace tokens in botdeploy.json'
      inputs:
        rootDirectory: 'whitewaterfinder.infrastructure/'
        targetFiles: botdeploy.json
        tokenPrefix: '{%%'
        tokenSuffix: '%%}'    

    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Or Update Resource Group action on waterfinder'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        resourceGroupName: '${{parameters.resourceGroup}}'
        location: '${{parameters.region}}'
        csmFile: 'whitewaterfinder.infrastructure/botdeploy.json'
        csmParametersFile: 'whitewaterfinder.infrastructure/botparams.json' 
        overrideParameters: '-botInsightsName "dev-paddle-finder"'        


