stages:
- stage: DeployGlobal
  jobs:
  - job: 'shared'
    pool:
      vmImage: 'windows-latest'
    steps:
              
    - task: AzureResourceGroupDeployment@2
      displayName: 'Build Global (Search) Resources'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        resourceGroupName: 'brgs-global' #this is a thing that needs to be addressed.
        location: '$(azureRegion)'
        csmFile: 'whitewaterfinder.infrastructure/global-services.json'
        csmParameetersFile: 'whitewaterfinder.infrastructure/global-services-params.json'

    - task: AzureCLI@2
      displayName: 'Build Azure Search Index'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        scriptType: ps
        scriptLocation: 'scriptPath'
        ScriptPath: 'whitewaterfinder.infrastructure/deployment.ps1'
        ScriptArguments: 'brgs-global "whitewaterfinder.infrastructure/riverswithid.json"'     