parameters:
- name: 'stageTitle'
  type: string
  default: ''
- name: 'environment'
  type: string
  default: ''
- name: 'resourceGroup'
  type: string
  default: ''
- name: 'region'
  type: string
  default: 'North Central US'
- name: 'storageAccountName'
  type: string
  default: ''
- name: 'storageAccountType'
  type: string
  default: 'Standard_LRS'
- name: 'appName'
  type: string
  default: ''

stages:
- stage: ${{parameters.stageTitle}}
  jobs:
  - job: 'backend_infra'
    pool:
      vmImage: 'windows-latest'
    steps:     
    - task: AzureResourceGroupDeployment@2
      displayName: 'Deploy Shared Azure Resources'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        resourceGroupName: '${{parameters.resourceGroup}}'
        location: '${{parameters.region}}'
        csmFile: 'whitewaterfinder.infrastructure/sharedresources.json'
        csmParametersFile: 'whitewaterfinder.infrastructure/sharedresourcesparams.json'
        overrideParameters: '-storageAccountType "${{parameters.storageAccountType}}" -appName "${{parameters.appName}}" -preferencesApp "${{parameters.appName}}-preferences" -storageAccountName "${{parameters.storageAccountName}}"'           

    - task: AzureCLI@2
      displayName: 'Get Azure Search Query Key'
      inputs: 
        azureSubscription: 'whitewaterfinder-sp'
        scriptType: ps
        scriptLocation: 'scriptPath'
        ScriptPath: 'whitewaterfinder.infrastructure/getazuresearchkey.ps1'
        ScriptArguments: 'brgs-global'   

    - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: 'Replace tokens in azuredeploy.json'
      inputs:
        rootDirectory: 'whitewaterfinder.infrastructure/'
        targetFiles: azuredeploy.json
        tokenPrefix: '{%%'
        tokenSuffix: '%%}'     

    - task: AzureResourceGroupDeployment@2
      displayName: 'Deploy backend ARM Template'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        resourceGroupName: '${{parameters.resourceGroup}}'
        location: '${{parameters.region}}'
        csmFile: 'whitewaterfinder.infrastructure/azuredeploy.json'
        csmParametersFile: 'whitewaterfinder.infrastructure/parameters.json'
        overrideParameters: '-storageAccountName ${{parameters.storageAccountName}} -storageAccountType "${{parameters.storageAccountType}}" -appName "${{parameters.appName}}" -appPlanName "WaterFinderPlan" -preferencesApp "${{parameters.appName}}-preferences"  -azureSearchKey $(searchKey)'       

    - task: AzureResourceGroupDeployment@2
      displayName: 'Deploy AKV'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        resourceGroupName: '${{parameters.resourceGroup}}'
        location: '${{parameters.region}}'
        csmFile: 'whitewaterfinder.infrastructure/kvtemplate.json'
        csmParametersFile: 'whitewaterfinder.infrastructure/kvparameters.json'
        overrideParameters: '-tenantId "$(tenantId)" -adminId "$(adminId)" -kvName "${{parameters.resourceGroup}}"'

  # - job: 'bot'
  #   dependsOn: 'backend_infra'
  #   pool:
  #     vmImage: 'windows-latest'
  #   steps:
  #   - task: AzureResourceGroupDeployment@2
  #     displayName: 'Deploy Cognitive Services'
  #     inputs:
  #       azureSubscription: 'whitewaterfinder-sp'
  #       resourceGroupName: '${{parameters.resourceGroup}}'
  #       location: '${{parameters.region}}'
  #       csmFile: 'whitewaterfinder.infrastructure/cognitiveservices.json'
  #       csmParamtersFile: 'whitewaterfinder.infrastructure/cogservicesparams.json'
  #       overrideParameters: '-luisName "dev-webster-luis" -authoringName "dev-webster-luis-authoring"'


  - deployment: 'bot'
    displayName: 'deploy cog services'
    pool:
      vmImage: 'windows-latest'
    environment: '${{parameters.environment}}'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureResourceGroupDeployment@2
            displayName: 'Deploy Cognitive Services'
            inputs:
              azureSubscription: 'whitewaterfinder-sp'
              resourceGroupName: '${{parameters.resourceGroup}}'
              location: '${{parameters.region}}'
              csmFile: 'whitewaterfinder.infrastructure/cognitiveservices.json'
              csmParamtersFile: 'whitewaterfinder.infrastructure/cogservicesparams.json'
              overrideParameters: '-luisName "dev-webster-luis" -authoringName "dev-webster-luis-authoring"'      

    # - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    #   displayName: 'Replace tokens in botdeploy.json'
    #   inputs:
    #     rootDirectory: 'whitewaterfinder.infrastructure/'
    #     targetFiles: botdeploy.json
    #     tokenPrefix: '{%%'
    #     tokenSuffix: '%%}'    

    # - task: AzureResourceGroupDeployment@2
    #   displayName: 'Azure Deployment:Create Or Update Resource Group action on waterfinder'
    #   inputs:
    #     azureSubscription: 'whitewaterfinder-sp'
    #     resourceGroupName: '${{parameters.resourceGroup}}'
    #     location: '${{parameters.region}}'
    #     csmFile: 'whitewaterfinder.infrastructure/botdeploy.json'
    #     csmParametersFile: 'whitewaterfinder.infrastructure/botparams.json' 
    #     overrideParameters: '-botInsightsName "dev-paddle-finder"'        


