stages:
- stage: Deploy_Global
  jobs:
  - job: 'shared'
    pool:
      vmImage: 'windows-latest'
    steps:

    - task: AzureResourceGroupDeployment@2
      displayName: 'Deploy Shared Azure Resources'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        resourceGroupName: $(resourceGroupDev)
        location: '$(azureRegion)'
        csmFile: 'whitewaterfinder.infrastructure/sharedresources.json'
        csmParametersFile: 'whitewaterfinder.infrastructure/sharedresourcesparams.json'
        overrideParameters: '-storageAccountType "Standard_LRS" -appName "dev-paddle-finder" -preferencesApp "dev-paddle-finder-preferences" -storageAccountName "dev-waterfinder"'                 
    
    - task: AzureResourceGroupDeployment@2
      displayName: 'Build Global (Search) Resources'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        resourceGroupName: 'brgs-global' #this is a thing that needs to be addressed.
        location: '$(azureRegion)'
        csmFile: 'whitewaterfinder.infrastructure/global-services.json'
        csmParameetersFile: 'whitewaterfinder.infrastructure/global-services-params.json'

    - task: AzureCLI@2
      displayName: 'Build Azure Search Index'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        scriptType: ps
        scriptLocation: 'scriptPath'
        ScriptPath: 'whitewaterfinder.infrastructure/deployment.ps1'
        ScriptArguments: 'brgs-global "whitewaterfinder.infrastructure/riverswithid.json"'     