parameters:
- name: 'stageTitle'
  type: string
- name: 'appName'
  type: string
  default: ''
  
stages:
- stage: ${{parameters.stageTitle}}
  jobs:
  - job: 'backend_app_deployment'
    pool:
      vmImage: 'windows-latest'

    steps:
    - download: current
      displayName: 'download river apis'
      artifact: riversfunc
    
    - task: AzureRmWebAppDeployment@3
      displayName: 'Deploy River API'
      inputs:
          azureSubscription: 'whitewaterfinder-sp'
          appType: functionapp
          WebAppName: '${{parameters.appName}}'
          Package: '$(Pipeline.Workspace)/riversfunc/app.zip'
          TakeAppOfflineFlag: true      
          
    - download: current
      displayName: 'download preferences apis'
      artifact: preferencesfunc
    
    - task: AzureRmWebAppDeployment@3
      displayName: 'Deploy Preferences API'
      inputs:
          azureSubscription: 'whitewaterfinder-sp'
          appType: functionapp
          WebAppName: '${{parameters.appName}}-preferences'
          Package: '$(Pipeline.Workspace)/preferencesfunc/app.zip'
          TakeAppOfflineFlag: true   