stages:
- stage: Deploy
  jobs:
  - job: 'shared'
    pool:
      vmImage: 'windows-latest'
    steps:

   

    - task: AzureResourceGroupDeployment@2
      condition: startsWith(variables['build.sourceBranch'], 'refs/tags/prod')
      displayName: 'Deploy Shared Azure Resources'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        resourceGroupName: $(resourceGroup)
        location: '$(azureRegion)'
        csmFile: 'whitewaterfinder.infrastructure/sharedresources.json'
        csmParametersFile: 'whitewaterfinder.infrastructure/sharedresourcesparams.json'
        overrideParameters: '-storageAccountType "Standard_LRS" -appName "paddle-finder" -preferencesApp "paddle-finder-preferences" '           

  - job: 'backend_infra'
    dependsOn: 'shared'
    pool:
      vmImage: 'windows-latest'
    steps:     
        
   


    - task: AzureCLI@2
      displayName: 'Get Azure Search Query Key'
      inputs: 
        azureSubscription: 'whitewaterfinder-sp'
        scriptType: ps
        scriptLocation: 'scriptPath'
        ScriptPath: 'whitewaterfinder.infrastructure/getazuresearchkey.ps1'
        ScriptArguments: '$(resourceGroup)'      
  

    - task: AzureResourceGroupDeployment@2
      displayName: 'Deploy backend ARM Template'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        resourceGroupName: $(resourceGroup)
        location: '$(azureRegion)'
        csmFile: 'whitewaterfinder.infrastructure/azuredeploy.json'
        csmParametersFile: 'whitewaterfinder.infrastructure/parameters.json'
        overrideParameters: '-storageAccountType "Standard_LRS" -appName "paddle-finder" -appPlanName "WaterFinderPlan" -preferencesApp "paddle-finder-preferences"  -azureSearchKey $(searchKey)'       
        
    - task: AzureCLI@2
      displayName: 'Build Azure Search Index'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        scriptType: ps
        scriptLocation: 'scriptPath'
        ScriptPath: 'whitewaterfinder.infrastructure/deployment.ps1'
        ScriptArguments: '$(resourceGroup) "whitewaterfinder.infrastructure/riverswithid.json"'
      
  - job: 'backend_app_deployment'
    pool:
      vmImage: 'windows-latest'
    dependsOn: 'backend_infra'
    steps:
    - download: current
      displayName: 'download river apis'
      artifact: riversfunc
    
    - task: AzureRmWebAppDeployment@3
      displayName: 'Deploy River API'
      inputs:
          azureSubscription: 'whitewaterfinder-sp'
          appType: functionapp
          WebAppName: 'paddle-finder'
          Package: '$(Pipeline.Workspace)/riversfunc/app.zip'
          TakeAppOfflineFlag: true      
          
    - download: current
      displayName: 'download preferences apis'
      artifact: preferencesfunc
    
    - task: AzureRmWebAppDeployment@3
      displayName: 'Deploy Preferences API'
      inputs:
          azureSubscription: 'whitewaterfinder-sp'
          appType: functionapp
          WebAppName: 'paddle-finder-preferences'
          Package: '$(Pipeline.Workspace)/preferencesfunc/app.zip'
          TakeAppOfflineFlag: true   


  - job: 'backend_security'
    pool:
      vmImage: 'windows-latest'
    dependsOn: 'backend_app_deployment'
    steps:
      
      
      - task: AzureResourceGroupDeployment@2
        displayName: 'Deploy APIM to waterfinder'
        inputs:
            azureSubscription: 'whitewaterfinder-sp'
            resourceGroupName: $(resourceGroup)
            location: '$(azureRegion)'
            csmFile: 'whitewaterfinder.infrastructure/apimdeploy.json'  
            csmParametersFile: 'whitewaterfinder.infrastructure/apimparameters.json'   
            overrideParameters: -adminEmail "$(adminEmail)"   
        
      - download: current
        artifact: infra

      - task: AzureCLI@2
        displayName: 'Configure APIM'
        inputs:
          azureSubscription: 'whitewaterfinder-sp'
          scriptType: ps
          scriptLocation: 'scriptPath'
          ScriptPath: '$(Pipeline.Workspace)/infra/apimdeploy.ps1'    
          azurePowerShellVersion: LatestVersion      
          ScriptArguments: '$(resourceGroup) $(Pipeline.Workspace)\infra'            

  - job: 'bot'
    dependsOn: 'backend_infra'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: 'Replace tokens in botdeploy.json'
      inputs:
        rootDirectory: 'whitewaterfinder.infrastructure/'
        targetFiles: botdeploy.json
        tokenPrefix: '{%%'
        tokenSuffix: '%%}'    

    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Or Update Resource Group action on waterfinder'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        resourceGroupName: $(resourceGroup)
        location: '$(azureRegion)'
        csmFile: 'whitewaterfinder.infrastructure/botdeploy.json'
        csmParametersFile: 'whitewaterfinder.infrastructure/botparams.json'         

    - download: current
      artifact: websterbot    

    - task: AzureRmWebAppDeployment@3
      displayName: 'Deploy Bot App'
      inputs:
        azureSubscription: 'whitewaterfinder-sp'
        appType: app
        WebAppName: 'WhiteWaterWebster'
        Package: '$(Pipeline.Workspace)/websterbot/publish.zip'
