
trigger:
    - master  

stages: 
- template: 'whitewaterfinder.pipeline/build.yml'
  parameters: 
    vstsFeed: 'e7750945-8da0-48c7-ad5d-6c474174e6d1'
    
- template: 'whitewaterfinder.pipeline/deployglobal.yml'
  parameters:
    environment: 'development'

- template: 'whitewaterfinder.pipeline/deployInfra.yml'
  parameters:
    environment: 'development'
    stageTitle: 'DeployDevInfrastructure'
    resourceGroup: '$(resourceGroupDev)'
    region: '$(azureRegion)'
    storageAccountName: "devwaterfinder"
    appName: "dev-paddle-finder"
    luisEndpointName: 'dev-webster-luis'
    luisAuthoring: 'dev-webster-luis-authoring'
    botName: 'WhiteWaterWebsterDev'

- template: 'whitewaterfinder.pipeline/deployApp.yml'
  parameters:
    stageTitle: "DevAppDeploy"
    appName: 'dev-paddle-finder'
    resourceGroup: '$(resourceGroupDev)'
    region: '$(azureRegion)'
    botapp: 'WhiteWaterWebsterDev'
    principal: 'whitewaterfinder-sp'
  
## Begin Production Deployment
# - template: 'whitewaterfinder.pipeline/deployInfra.yml'
#   parameters:
#     environment: 'production'
#     stageTitle: 'DeployProdInfrastructure'
#     resourceGroup: '$(resourceGroup)'
#     region: '$(azureRegion)'
#     storageAccountName: "waterfinder"
#     appName: "paddle-finder"
#     luisEndpointName: 'webster-luis'
#     luisAuthoring: 'webster-luis-authoring'   
#     botName: 'WhitewaterWebster' 

# - template: 'whitewaterfinder.pipeline/deployApp.yml'
#   parameters:
#     environment: 'production'
#     stageTitle: "ProdAppDeploy"
#     appName: 'paddle-finder'
#     resourceGroup: '$(resourceGroupDev)'
#     region: '$(azureRegion)'
#     botapp: 'WhiteWaterWebster'
#     principal: 'whitewaterfinder-sp'





 
        