
trigger:
    - master  

stages: 
- template: 'pipeline-templates/build.yml'
- template: 'pipeline-templates/deployglobal.yml'

- template: 'pipeline-templates/deployInfra.yml'
  parameters:
    stageTitle: 'DeployDevInfrastructure'
    resourceGroup: '$(resrourceGroupDev)'
    region: '$(azureRegion)'
    storageAccountName: "devwaterfinder"
    appName: "dev-paddle-finder"

- template: 'pipeline-templates/deployInfra.yml'
  parameters:
    stageTitle: 'DeployProdInfrastructure'
    resourceGroup: '$(resrourceGroup)'
    region: '$(azureRegion)'
    storageAccountName: "waterfinder"
    appName: "paddle-finder"

- template: 'pipeline-templates/deployApp.yml'
  parameters:
    stageTitle: "DevAppDeploy"
    appName: 'dev-paddle-finder'
    resourceGroup: '$(resrourceGroupDev)'
    region: '$(azureRegion)'




 
        