
trigger: 
  - trunk

stages: 
- template: 'whitewaterfinder.pipeline/build.yml'
  parameters: 
    vstsFeed: $(artifactKey)
    
- template: 'whitewaterfinder.pipeline/deployglobal.yml'
  parameters:
    environment: 'development'
    sharedRg: 'waterfinder'
    principal: '$(principal)'
    region: '$(azureRegion)'
    
    
- template: 'whitewaterfinder.pipeline/deployInfra.yml'
  parameters:
    environment: 'development'
    stageTitle: 'DeployDevInfrastructure'
    resourceGroup: '$(resourceGroupDev)'
    sharedRg: '$(resourceGroupDev)'
    region: '$(azureRegion)'
    storageAccountName: "$(resourceGroupDev)"
    appName: "paddle-finder"
    luisEndpointName: 'webster-luis'
    luisAuthoring: 'webster-luis-authoring'
    botName: 'WhiteWaterWebsterDev'
    principal: '$(principal)'
    tenant: '$(tenantId)'
    adminEmail: '$(adminEmail)'
    adminId: '$(adminId)'


- template: 'whitewaterfinder.pipeline/deployApp.yml'
  parameters:
    stageTitle: "DevAppDeploy"
    appName: 'paddle-finder'
    resourceGroup: '$(resourceGroupDev)'
    region: '$(azureRegion)'
    botapp: 'WhiteWaterWebsterDev'
    principal: '$(principal)'
    adminEmail: '$(adminEmail)'
  
## Begin Production Deployment
# - template: 'whitewaterfinder.pipeline/deployInfra.yml'
#   parameters:
#     environment: 'production'
#     stageTitle: 'DeployProdInfrastructure'
#     resourceGroup: '$(resourceGroup)'
#     region: '$(azureRegion)'
#     storageAccountName: "waterfinder"
#     appName: "paddle-finder"
#     luisEndpointName: 'webster-luis'
#     luisAuthoring: 'webster-luis-authoring'   
#     botName: 'WhitewaterWebster' 

# - template: 'whitewaterfinder.pipeline/deployApp.yml'
#   parameters:
#     environment: 'production'
#     stageTitle: "ProdAppDeploy"
#     appName: 'paddle-finder'
#     resourceGroup: '$(resourceGroupDev)'
#     region: '$(azureRegion)'
#     botapp: 'WhiteWaterWebster'
#     principal: '$(principal)'





 
        