resources:

- repo: self
  clean: true

trigger:
    - master  
    - feature/ARM-template


queue:
  name: Hosted Ubuntu 1604

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'set node environment' 


- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'
    vstsFeed: 'e7750945-8da0-48c7-ad5d-6c474174e6d1'

- script: npm install && npm run build
  displayName: 'build User Pref functions'
  workingDirectory: whitewaterfinder.api.user

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*[Tt]est/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish River Functions'
  inputs:
    PathtoPublish: whitewaterfinder.api/bin/release/netstandard2.0
    ArtifactName: 'riversfunc'

- task: PublishBuildArtifacts@1
  displayName: 'Copy ARM'
  inputs:
    PathtoPublish: whitewaterfinder.infrastructure
    ArtifactName: 'infra'


- task: PublishBuildArtifacts@1
  displayName: 'Copy Preferences Functions'
  inputs:
    PathtoPublish: whitewaterfinder.api.user
    ArtifactName: 'preferencesfunc'