
trigger: 
  - trunk
  - refactor/pipeline-refactoring

stages: 
- template: 'whitewaterfinder.pipeline/build.yml'
  parameters: 
    vstsFeed: $(artifactKey)
    principal: $(principal)
    providerstorage: 'tfstatewaterfinder'
    resourceGroup: $(resourceGroupDev)
    region: '$(azureRegion)'
    appName: "paddle-finder"    
    adminEmail: '$(adminEmail)'
    adminId: '$(adminId)' 
    tenant: '$(tenantId)' 
    storageAccountName: "$(resourceGroupDev)" 



    
    


# - template: 'whitewaterfinder.pipeline/deployApp.yml'
#   parameters:
#     stageTitle: "DevAppDeploy"
#     appName: 'paddle-finder'
#     resourceGroup: '$(resourceGroupDev)'
#     region: '$(azureRegion)'
#     botapp: 'WhiteWaterWebsterDev'
#     principal: '$(principal)'
#     adminEmail: '$(adminEmail)'        