parameters:
- name: vstsFeed
  type: string
  default: ''
- name: principal
  type: string
  default: ''
- name: providerstorage
  type: string
  default: 'tfstatewaterfinder'
- name: resourceGroup
  type: string
  default: ''


stages:
- stage: Build
  jobs:
  - job: build_infra
    pool:
      vmImage: 'windows-latest'
    continueOnError: false
    steps:

    - task: AzureResourceGroupDeployment@2
      displayName: 'Deploy APIM to waterfinder'
      inputs:
          azureSubscription: '${{ parameters.principal }}'
          resourceGroupName: '${{ parameters.resourceGroup }}'
          location: '${{parameters.region}}'
          csmFile: 'whitewaterfinder.infrastructure/apim/apimdeploy.json'  
          csmParametersFile: 'whitewaterfinder.infrastructure/apim/apimparameters.json'   
          overrideParameters: '-adminEmail "${{ parameters.adminEmail }}" -appName "${{ parameters.appName }}" -preferencesApp "${{ parameters.appName }}-preferences"'   


  - job: build_dotnet
    pool:
      vmImage: 'windows-latest'
    continueOnError: false
    steps:
    - template: 'buildDotnet.yml'   
      parameters:
        vstsFeed: '${{parameters.vstsFeed}}' 

  - job: build_node
    pool:
      vmImage: 'windows-latest'
    continueOnError: false
    steps:
    - template: 'buildNode.yml'
