parameters:
- name: vstsFeed
  type: string
  default: ''
stages:
- stage: Build
  jobs:
  - job: build_infra
    pool:
      vmImage: 'windows-latest'
    continueOnError: false
    steps:
      - task: PublishBuildArtifacts@1
        displayName: 'Push infra scripts'
        inputs:
          PathtoPublish: 'whitewaterfinder.infrastructure/'
          ArtifactName: infra      

  - job: build_dotnet
    pool:
      vmImage: 'windows-latest'
    continueOnError: false
    steps:
    - template: 'buildDotnet.yml'
      parameters:
        vstsFeed: '${{parameters.vstsFeed}}'

  - job: build_node
    pool:
      vmImage: 'windows-latest'
    continueOnError: false
    steps:
    - template: 'buildNode.yml'

