parameters:
- name: 'environment'
  type: string
  default: ''
- name: 'sharedRg'
  type: string
  default: 'shared'
- name: 'principal'
  type: string
  default: ''  
- name: 'region' 
  type: string
  default: ''
- name: artifact
  type: string
  default: ''

stages:
- stage: ConfigureSearch
  jobs:
  - deployment: 'search'
    pool:
      vmImage: 'windows-latest'
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            displayName: download ${{ parameters.artifact }}
            artifact: ${{ parameters.artifact }}
          - task: AzureCLI@2
            displayName: 'Build Azure Search Index'
            inputs:
              azureSubscription: '${{ parameters.principal }}'
              scriptType: ps
              scriptLocation: 'scriptPath'
              ScriptPath: '$(Pipeline.Workspace)/${{ parameters.artifact }}/deployment.ps1'
              ScriptArguments: '${{ parameters.sharedRg }} "$(Pipeline.Workspace)/${{ parameters.artifact }}/riverswithid.json"'     