parameters:
- name: 'environment'
  type: string
  default: ''
- name: 'sharedRg'
  type: string
  default: 'shared'
- name: 'principal'
  type: string
  default: ''  
- name: 'region' 
  type: string
  default: ''
- name: artifact
  type: string
  default: ''

stages:
- stage: ConfigureSearch
  jobs:

  - deployment: 'search'
    pool:
      vmImage: 'ubuntu-latest'
    environment: ${{ parameters.environment }}

    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            displayName: download ${{ parameters.artifact }}
            artifact: ${{ parameters.artifact }}

          # - task: AzureCLI@2
          #   displayName: 'Build Azure Search Index'
          #   inputs:
          #     azureSubscription: '${{ parameters.principal }}'
          #     scriptType: ps
          #     scriptLocation: 'scriptPath'
          #     ScriptPath: '$(Pipeline.Workspace)/${{ parameters.artifact }}/deployment.ps1'
          #     ScriptArguments: '${{ parameters.sharedRg }} "$(Pipeline.Workspace)/${{ parameters.artifact }}/riverswithid.json"'   
          - download: current
            displayName: pull function keys
            artifact: variables
          - pwsh: |
              $rawKeys = Get-Content -Path $(Pipeline.Workspace)/variables/functionkeys.log
              Write-Host $rawKeys
          # - task: AzureCLI@2
          #   displayName: 'Configure APIM'
          #   inputs:
          #     azureSubscription: '${{parameters.principal}}'
          #     scriptType: ps
          #     scriptLocation: 'scriptPath'
          #     ScriptPath: '$(Pipeline.Workspace)/infra/apim/apimdeploy.ps1'    
          #     azurePowerShellVersion: LatestVersion      
          #     ScriptArguments: '${{ parameters.resourceGroup }} $(Pipeline.Workspace)\infra'                   