parameters:
- name: 'stageTitle'
  type: string
  default: ''
- name: 'environment'
  type: string
  default: ''
- name: 'resourceGroup'
  type: string
  default: ''
- name: 'sharedRg'
  type: string
  default: ''
- name: 'region'
  type: string
  default: 'North Central US'
- name: 'storageAccountName'
  type: string
  default: ''
- name: 'storageAccountType'
  type: string
  default: 'Standard_LRS'
- name: 'appName'
  type: string
  default: ''
- name: 'luisEndpointName'
  type: string
  default: ''
- name: 'luisAuthoring'
  type: string
  default: ''
- name: 'botName'
  type: string
  default: ''
- name: 'principal'
  type: string
  default: ''  
- name: 'tenant'
  type: string
  default: ''
- name: 'adminId'
  type: string
  default: ''
- name: 'adminEmail'
  type: string
  default: ''




stages:
- stage: ${{parameters.stageTitle}}
  jobs:
  - deployment: 'backend_infra'
    pool:
      vmImage: 'windows-latest'
    environment: ${{parameters.environment}}
    strategy:
      runOnce:
        deploy:
          steps:   
          - template:  'buildSearch.yml'
            parameters:
              storageAccountType: ${{ parameters.storageAccountType }}
              storageAccountName: ${{ parameters.storageAccountName }}
              appName: ${{ parameters.appName }}
              resourceGroup: ${{ parameters.resourceGroup }}
              sharedRg: ${{ parameters.sharedRg }}
              region: ${{ parameters.region }}
              principal: ${{ parameters.principal }}
   

          - task: AzureResourceGroupDeployment@2
            displayName: 'Deploy backend ARM Template'
            inputs:
              azureSubscription: '${{ parameters.principal }}'
              resourceGroupName: '${{ parameters.resourceGroup }}'
              location: '${{parameters.region}}'
              csmFile: '$(Pipeline.Workspace)/infra/azuredeploy.json'
              csmParametersFile: '$(Pipeline.Workspace)/infra/parameters.json'
              overrideParameters: '-storageAccountName ${{parameters.storageAccountName}} -storageAccountType "${{ parameters.storageAccountType }}" -appName "${{ parameters.appName }}" -appPlanName "WaterFinderPlan" -preferencesApp "${{ parameters.appName }}-preferences"  -azureSearchKey $(searchKey)'       

          - task: AzureResourceGroupDeployment@2
            displayName: 'Deploy Sendgrid'
            inputs:
              azureSubscription: '${{ parameters.principal }}'
              resourceGroupName: '${{ parameters.resourceGroup }}'
              location: '${{ parameters.region }}'
              csmFile: '$(Pipeline.Workspace)/infra/communications/communicationdeploy.json'
              csmParametersFile: '$(Pipeline.Workspace)/infra/communications/communicationdeployparams.json'
              overrideParameters: '-password "$(sendgridpassword)" -email "${{ parameters.adminEmail }}" -website "$(adminwebsite)"'

          - task: AzureResourceGroupDeployment@2
            displayName: 'Deploy AKV'
            inputs:
              azureSubscription: '${{ parameters.principal }}'
              resourceGroupName: '${{parameters.resourceGroup}}'
              location: '${{parameters.region}}'
              csmFile: '$(Pipeline.Workspace)/infra/keyvault/kvtemplate.json'
              csmParametersFile: '$(Pipeline.Workspace)/infra/keyvault/kvparameters.json'
              overrideParameters: '-tenantId "${{ parameters.tenantId }}" -adminId "${{ parameters.adminId }}" -kvName "${{parameters.resourceGroup}}"'

  - deployment: 'bot'
    dependsOn: 'backend_infra'
    pool:
      vmImage: 'windows-latest'
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: infra
          - task: AzureResourceGroupDeployment@2
            displayName: 'Deploy Cognitive Services'
            inputs:
              azureSubscription: '${{ parameters.principal }}'
              resourceGroupName: '${{parameters.resourceGroup}}'
              location: '${{parameters.region}}'
              csmFile: '$(Pipeline.Workspace)/infra/cognitiveservices/cognitiveservices.json'
              csmParametersFile: '$(Pipeline.Workspace)/infra/cognitiveservices/cogservicesparams.json'
              overrideParameters: '-luisName "${{parameters.luisEndpointName}}" -authoringName "${{parameters.luisAuthoring}}"'  
 
          - task: AzureCli@2
            displayName: 'create or pull MSFT App ID'
            inputs:
              azureSubscription: '${{ parameters.principal }}'
              scriptType: ps
              scriptLocation: 'scriptPath'
              ScriptPath: '$(Pipeline.Workspace)/infra/app-registration-create.ps1'
              ScriptArguments: '"${{ parameters.botName }}-ar"'
                

          - task: AzureResourceGroupDeployment@2
            displayName: 'Azure Deployment:Create Or Update Resource Group action on waterfinder'
            inputs:
              azureSubscription: '${{ parameters.principal }}'
              resourceGroupName: '${{parameters.resourceGroup}}'
              location: '${{parameters.region}}'
              csmFile: '$(Pipeline.Workspace)/infra/cognitiveservices/botdeploy.json'
              csmParametersFile: '$(Pipeline.Workspace)/infra/cognitiveservices/botparams.json' 
              overrideParameters: '-botInsightsName "${{ parameters.appName }}" -botAppName "${{parameters.botName}}" -msftAppId "$(newAppId)" -storageAccountName ${{parameters.storageAccountName}}'        


