parameters:
- name: 'environment'
  type: string
  default: ''
- name: 'stageTitle'
  type: string
- name: 'appName'
  type: string
  default: ''
- name: 'resourceGroup'
  type: string
  default: ''
- name: 'region'
  type: string
  default: 'North Central US'  
- name: 'botapp'
  type: string
  default: ''
- name: 'principal'
  type: string
  default: ''
- name: 'adminEmail'
  type: string
  default: ''
- name: 'adminApp'
  type: string
  default: ''

stages:
- stage: ${{ parameters.stageTitle }}
  jobs:
  - job: 'backend_app_deployment'
    pool:
      vmImage: 'windows-latest'
    continueOnError: true

    steps:
    - template: 'downloadAndDeploy.yml'
      parameters:
        artifact: riversfunc
        appType: functionapp
        principal: '${{ parameters.principal }}'
        appName: "${{ parameters.appName }}"

    - template: 'downloadAndDeploy.yml'
      parameters:
        artifact: preferencesfunc
        appType: functionapp
        principal: '${{ parameters.principal }}'
        appName: '${{ parameters.appName }}-preferences'      

    - template: 'downloadAndDeploy.yml'
      parameters:
        artifact: adminfunc
        appType: app
        principal: '${{ parameters.principal }}'
        appName: '${{ parameters.adminApp }}'
                     
    - template: 'downloadAndDeploy.yml'
      parameters: 
        artifact: botfunc
        appType: app
        principal: '${{ parameters.principal }}'
        appName: '${{ parameters.botapp }}'  

