parameters:
- name: 'environment'
  type: string
  default: ''
- name: 'sharedRg'
  type: string
  default: 'shared'
- name: 'principal'
  type: string
  default: ''  

stages:
- stage: DeployGlobal
  jobs:
  - deployment: 'shared'
    pool:
      vmImage: 'windows-latest'
    environment: ${{parameters.environment}}
    strategy:
      runOnce:
        deploy:
          steps:
                    
          - task: AzureResourceGroupDeployment@2
            displayName: 'Build Global (Search) Resources'
            inputs:
              azureSubscription: '${{ parameters.principal }}'
              resourceGroupName: '${{ parameters.sharedRg }}'
              location: '$(azureRegion)'
              csmFile: '$(Pipeline.Workspace)/infra/global/global-service.json'
              csmParameetersFile: '$(Pipeline.Workspace)/infra/global/global-service-params.json'

          - task: AzureCLI@2
            displayName: 'Build Azure Search Index'
            inputs:
              azureSubscription: '${{ parameters.principal }}'
              scriptType: ps
              scriptLocation: 'scriptPath'
              ScriptPath: '$(Pipeline.Workspace)/infra/deployment.ps1'
              ScriptArguments: '${{ parameters.sharedRg }} "$(Pipeline.Workspace)/infra/riverswithid.json"'     