parameters:
- name: 'environment'
  type: string
  default: ''
- name: 'stageTitle'
  type: string
- name: 'appName'
  type: string
  default: ''
- name: 'resourceGroup'
  type: string
  default: ''
- name: 'region'
  type: string
  default: 'North Central US'  
- name: 'botapp'
  type: string
  default: ''
- name: 'principal'
  type: string
  default: ''
- name: 'adminEmail'
  type: string
  default: ''

stages:
- stage: ${{parameters.stageTitle}}
  jobs:
  # - job: 'backend_app_deployment'
  #   pool:
  #     vmImage: 'windows-latest'

  #   steps:
  #   - template: 'downloadAndDeploy.yml'
  #     parameters:
  #       artifact: riversfunc
  #       appType: functionapp
  #       principal: '${{ parameters.principal }}'
  #       appName: "${{ parameters.appName }}"

  #   - template: 'downloadAndDeploy.yml'
  #     parameters:
  #       artifact: preferencesfunc
  #       appType: functionapp
  #       principal: '${{ parameters.principal }}'
  #       appName: '${{ parameters.appName }}-preferences'      
        

  #   - template: 'downloadAndDeploy.yml'
  #     parameters: 
  #       artifact: websterbot
  #       appType: app
  #       principal: '${{ parameters.principal }}'
  #       appName: '${{ parameters.botapp }}'  

  - job: 'backend_security'
    pool:
      vmImage: 'windows-latest'
    # dependsOn: 'backend_app_deployment'

    steps:

    - powershell: |
        Write-Host $env:riversKey
        Write-Host $env:usersKey
      env:
        riversKey: $(riversKey)
        userKey: $(usersKey)
    # - task: AzureCLI@2
    #   displayName: 'Configure APIM'
    #   inputs:
    #     azureSubscription: '${{parameters.principal}}'
    #     scriptType: ps
    #     scriptLocation: 'scriptPath'
    #     ScriptPath: '$(Pipeline.Workspace)/infra/apim/apimdeploy.ps1'    
    #     azurePowerShellVersion: LatestVersion      
    #     ScriptArguments: '${{ parameters.resourceGroup }} $(Pipeline.Workspace)\infra'      
               