jobs:
- job: 'shared'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: AzureResourceGroupDeployment@2
    displayName: 'Deploy Shared Azure Resources'
    inputs:
      azureSubscription: 'whitewaterfinder-sp'
      resourceGroupName: $(resourceGroup)
      location: '$(azureRegion)'
      csmFile: 'whitewaterfinder.infrastructure/sharedresources.json'
      csmParametersFile: 'whitewaterfinder.infrastructure/sharedresourcesparams.json'
      overrideParameters: '-storageAccountType "Standard_LRS" -appName "paddle-finder" -preferencesApp "paddle-finder-preferences" '           

  - task: AzureCLI@2
    displayName: 'Get Azure Search Query Key'
    inputs: 
      azureSubscription: 'whitewaterfinder-sp'
      scriptType: ps
      scriptLocation: 'scriptPath'
      ScriptPath: 'whitewaterfinder.infrastructure/getazuresearchkey.ps1'
      ScriptArguments: '$(resourceGroup)'   