on:
  push:
    branches:
      - trunk
    paths:
      - 'whitewaterfinder.api.rivers/**'
      - 'whitewaterfinder.Core.Rivers/**'
      - 'whitewaterfinder.Repo.Rivers/**'
      - 'whitewaterfinder.BusinessObjects/**'
      - '.github/workflows/api.rivers.yml'
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'whitewaterfinder.api.rivers'
jobs:
  build-and-test-rivers-api:
    uses: badgerowluke/.github/.github/workflows/ru-functions-build.yaml@main
    secrets: inherit
    with:
      WORKING_DIR: 'whitewaterfinder.api.rivers'
      PUBLISH_FOLDER_NAME: 'rivers'
      GHUSER: ${{ github.USER }}
      GHTOKEN: ${{ github.TOKEN }}
