on:
  push:
    branches:
      - trunk
    paths:
      - 'whitewaterfinder.api.admin/**'
      - '.github/workflows/api.admin.yml'


env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'whitewaterfinder.api.admin'      

jobs:
  build-and-test-admin-api:
    uses: badgerowluke/.github/.github/workflows/ru-functions-build.yaml@main
    secrets: inherit
    with:
      WORKING_DIR: 'whitewaterfinder.api.admin'
      PUBLISH_FOLDER_NAME: 'admin'
      GHUSER: ${{ secrets.GH_USER }}
      GHTOKEN: ${{ secrets.GH_TOKEN }}
      GHPACKAGES: ${{ secrets.GH_PACKAGES }}

