#because GHA doesn't allow manual runs 3
          #  
on:
  push:
    branches:
      - trunk
    paths:
      - 'whitewaterfinder.api.bot/**'
      - '.github/workflows/api.bot.yml'

jobs:
  build-test-deploy:
    uses: badgerowluke/.github/.github/workflows/ru-functions-build.yaml@main
    secrets: inherit
    with:
      WORKING_DIR: 'whitewaterfinder.api.bot'
      PUBLISH_FOLDER_NAME: 'bot'

