on:
  push:
    branches:
      - trunk
    paths:
      - 'whitewaterfinder.api.monitoring/**'
      - '.github/workflows/api.monitoring.yml'


env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'whitewaterfinder.api.monitoring'      

jobs:
  build-and-test-monitoring-api:

    uses: badgerowluke/.github/.github/workflows/ru-functions-build.yaml@main
    secrets: inherit
    with:
      WORKING_DIR: 'whitewaterfinder.api.monitoring'
      PUBLISH_FOLDER_NAME: 'monitoring'
      GHUSER: ${{ github.USER }}
      GHTOKEN: ${{ github.TOKEN }}