#use this line for any meaningless changes that need to be made since GHA doesn't have a manual run 1
on:
  push:
    branches:
      - trunk
    paths:
      - 'whitewaterfinder.api.user/**'
jobs:
  build-and-test:
    name: "build and test"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 'whitewaterfinder.api.user'
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: 'build user pref functions'
        run: |
          npm install && npm run build

      - name: az login
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZCLI_CREDS }}
      
      - name: build container
        run: |

          az acr login --name paddlefinderregistry 
          docker build . --file Dockerfile --tag paddlefinderregistry.azurecr.io/whitewaterfinder.api.user:$GITHUB_RUN_ID
          docker push paddlefinderregistry.azurecr.io/whitewaterfinder.api.user:$GITHUB_RUN_ID  