#because GHA doesn't allow manual runs 3
          #  
on:
  push:
    branches:
      - trunk
    paths:
      - 'whitewaterfinder.api.bot/**'
      - '.github/workflows/api.bot.yml'

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'whitewaterfinder.api.bot'      

jobs:
  build-and-test-bot-api:
    # needs: terraform
    name: "build and test the chatbot api"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash



    steps:
      - name: "checkout"
        uses: actions/checkout@v2.1.0


      - name: setup dotnet 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          
      - name: az login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZCLI_CREDS }}

      - name: build test and publish
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: |
          dotnet nuget add source --username ${{ secrets.GH_USER }} --password ${{ secrets.GH_TOKEN }} --store-password-in-clear-text --name github "${{ secrets.GH_PACKAGES }}"        
          dotnet restore
          dotnet build --no-restore --configuration Release
          dotnet test --no-build --verbosity normal
          dotnet publish --no-restore -c Release -o './publish/bot'

      - name: deploy to funtionapp
        uses: azure/webapps-deploy@v2
        with: 
          app-name: 'paddle-finder-webster'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/publish/bot'

      - name: logout
        run: az logout