on:
  push:
    branches:
    - trunk
    paths: 
      - 'whitewaterfinder.pwa/paddle-finder/**'
      - '.github/workflows/front.paddlefinder.yml'
jobs:
  build-and-deploy:
    name: 'build'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'whitewaterfinder.pwa/paddle-finder'
    steps:
    
      - name: "checkout"
        uses: actions/checkout@v2.1.0   


      - name: az login
        uses: azure/login@v1
        with:
          creds: ${{ secrets. AZCLI_CREDS }}

      - name: get secrets
        uses: Azure/get-keyvault-secrets@v1
        id: getSecrets
        with:
          keyvault: "paddle-finder"
          secrets: 'apim-master-key, instrumentKey, storageKey'


      - name: "apply config"
        shell: pwsh

        run: |
          $json = @"
          {
            "auth": {
              "domain": "${{ secrets.AUTH0DOMAIN }}",
              "clientId": "${{ secrets.AUTH0CLIENTID }}"
            },
            "insights": {
              "instrumentationKey": "${{ steps.getSecrets.outputs.instrumentKey }}"
            },
            "backend": {
              "apiUrl": "https://whitewater-finder.azure-api.net",
              "subscriptionKey":"${{ steps.getSecrets.outputs.apim-master-key }}"
            },
            "production": true
          }
          "@
          
          New-Item -ItemType directory -Path src/assets/config
          $json | ConvertTo-Json | Out-File 'src/assets/config/config.json' 


      - uses: LanceMcCarthy/Action-AzureBlobUpload@v1.9.0
        name: Azure Blob Upload with Destination folder defined
        with:
          connection_string: ${{ secrets.YourAzureBlobConnectionString }}
          container_name: archive
          source_folder: whitewaterfinder.pwa/paddle-finder/dist
          destination_folder: $GITHUB_RUN_ID
          clean_destination_folder: true


      - name: logout
        run: az logout            

      - name: deploy to netlify
        working-directory: whitewaterfinder.pwa/paddle-finder
        env: 
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_APP_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        run: |
          npm i g netlify-cli
          npm i  && npm run build-prod
          netlify deploy --prod --dir ./dist/paddle-finder
          